from enum import Enum, unique

@unique
class TokenType(Enum):
    IDENTIFIER = 1,
    NUMBER = 2,
    STRING = 3,
    CHARACTER = 4,
    ARITHMETIC_ADDITION = 5,
    ARITHMETIC_SUBTRACTION = 6,
    ARITHMETIC_MULTIPLICATION = 7,
    ARITHMETIC_DIVIDER = 8,
    EQUAL = 9
    DIFFERENT = 10,
    GREATER_THAN = 11,
    GREATER_EQUAL_THAN = 12,
    LESS_THAN = 13,
    LESS_EQUAL_THAN = 14, 
    AND = 15,
    OR = 16,
    ASSIGNMENT = 17,
    INCREMENT = 18,
    DECREMENT = 19,
    DOT_OPERATOR = 20,
    SEMICOLON = 21,
    COMMA = 22,
    OPEN_PARENTHESIS = 23,
    CLOSE_PARENTHESIS = 24,
    OPEN_CURLY_BRACE = 25,
    CLOSE_CURLY_BRACE = 26,
    OPEN_SQUARE_BRACKET = 27,
    CLOSE_SQUARE_BRACKET = 28,
    BLOCK_COMMENT = 29,
    LINE_COMMENT = 30,
    NUMBER_ERROR = 31,
    STRING_ERROR = 32,  
    CHARACTER_INVALID = 33,
    MISSING_QUOTES = 34,
    OVERFLOW = 35,
    BLOCK_COMMENT_ERROR = 36
  



